apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-app
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/andrews326/chat.git
    targetRevision: main  # Or specify the branch/tag/commit you want to deploy
    path: /  # Path to the root directory of your repository
  destination:
    server: 'https://kubernetes.default.svc'  # URL of your Kubernetes cluster
    namespace: default
  syncPolicy:
    automated: {}
